# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

# Browsers
"brave" = ""
"chromium" = ""
"firefox" = ""

# Apps
"alacritty" = ""
"blender" = ""
"gimp" = ""
"inkscape" = ""
"krita" = ""
"libreoffice calc" = ""
"libreoffice impress" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"qemu" = ""
"signal" = ""
"steam" = ""

# Websites
"github" = ""
"linkedin" = ""
"pinterest" = ""
"reddit" = ""
"twitter" = ""
"youtube" = ""

# File types
".pdf" = ""

[other]
fallback_icon = ""
deduplicate_icons = true
